---
title: "Final_Project"
author: "Nathan Shiosaki and Reza Naiman"
date: "3/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


to get the dates to work for the CPI data, I had to install the zoo library for the as.yearmon function
```{r pressure, echo=FALSE, warning=FALSE}
library(tidyverse)
library(zoo)
library(dslabs)
library(caret)
library(stringr)
library(ggplot2)
library(dplyr)
library(tibble)
library(lubridate)
CPI_data <- read.csv("CPI_data.csv")
Covid_data <- read.csv("trends_in_covid19_cases_and_deaths_in_the_us_reported_to_cdc_by_population_factors.csv")
Alaska_Covid_data <- read.csv("Alaska_data.csv")
Alaska_CPI <- read.csv("CPI_Data_Alaska.csv")
World_Covid_data <- read.csv("WHO-COVID-19-global-data.csv")
Finland_CPI_data <- read.csv("Finland_CPI_data.csv")
```


```{r}
#filtering the urban areas and setting the dates to date variables
Clean_Covid_Data <- Covid_data %>% filter(Classification == "Metro_Rural") %>% filter(Category == 1)
Clean_Covid_Data <- Clean_Covid_Data %>% mutate(Date = as.Date(Clean_Covid_Data$Date, format = "%m/%d/%Y")) 

#filtering out Finland and setting the dates to date variables
Finland_Covid_data <- World_Covid_data %>% filter(Country == "Finland") %>% rename(Date=ï..Date_reported) 
Finland_Covid_data <- Finland_Covid_data %>% mutate(Date = as.Date(Finland_Covid_data$Date, format = "%Y-%m-%d")) 

#filtering the urban areas and setting the dates to date variables
urban_alaska <- Alaska_Covid_data %>% filter(Community == "Anchorage" | Community == "Fairbanks") %>% group_by(Date.Reported) %>% mutate(Total_Cases = sum(All.Cases)) %>% distinct(Date.Reported,.keep_all = TRUE) %>% rename(Date=Date.Reported)
urban_alaska$Date <- as.Date(urban_alaska$Date, format = "%m/%d/%Y") 
head(urban_alaska)

#setting the dates to date variable for the CPI data
CPI_data <- CPI_data %>%  mutate(Date = as.Date(as.yearmon(CPI_data$Date, format = '%Y-%B')))
Alaska_CPI <- Alaska_CPI %>% mutate(Date = as.Date(as.yearmon(Alaska_CPI$Date, format = '%Y-%B')))
Finland_CPI_data <- Finland_CPI_data %>%  mutate(Date = as.Date(as.yearmon(Finland_CPI_data$Date, format = '%y-%b')))

#Combining Covid data and CPI data into a single dataframe for statistical analysis
Finland_data <- inner_join(Finland_CPI_data, Finland_Covid_data)
Alaska_data <- inner_join(Alaska_CPI, urban_alaska)
All_Data <- inner_join(CPI_data, Clean_Covid_Data)

```


```{r}
CPI_data %>% ggplot(aes(Date, Bread)) + geom_line()
tail(Clean_Covid_Data)
Clean_Covid_Data  %>% ggplot(aes(Date, X7.Day.Avg.New.Cases.per.100K)) + geom_line()

All_Data %>% ggplot(aes(X7.Day.Avg.New.Cases.per.100K, Educational.books.and.supplies)) + geom_point()

CPI_data

#Filtering the data between when covid first started until the FEB 2022
#----------------------------------------------------------------------
CPI_covid_data <- CPI_data %>% filter(Date >= '2020-01-01')
Covid_data_endFeb <- Clean_Covid_Data %>% filter(Date < '2022-02-26')
#----------------------------------------------------------------------


#tail(Covid_data_endFeb)
#tail(CPI_covid_data)



#CPI_covid_data
#Covid_data_endFeb

months <- as_tibble(c())
months['monthname'] <- NA
months['monthcases'] <- NA

months

mymonths <-c("2020JAN", "2020FEB", "2020MAR", "2020APR", "2020MAY", "2020JUN", "2020JUL", "2020AUG", "2020SEP", "2020OCT", "2020NOV", "2020DEC", "2021JAN", "2021FEB", "2021MAR", "2021APR", "2021MAY", "2021JUN", "2021JUL", "2021AUG", "2021SEP", "2021OCT", "2021NOV", "2021DEC", "2022JAN", "2022FEB")

for(i in 1:26){
 months[i, ] <- NA
}
for(i in 1:26){
  months$monthname[i] <- mymonths[i]
}


covmonthly <- as_tibble(c())

Covid_data_endFeb


Covid_data_endFeb$newcases <- 0



for(i in 2:767)
{
  Covid_data_endFeb$newcases[i] <- Covid_data_endFeb$Total.Cases.per.100K[i] - Covid_data_endFeb$Total.Cases.per.100K[i-1]
}
#create a new column which indicates new cases each day 



```

```{R}

myvec <- c()


#myvec[1:26] <- 0


v <- 3
start <- 37 
c1 <- 30
c2 <- 31 

for(i in 1:11){
  sum <- 0 
  if(i %% 2 != 0)
  {
    sum <- 0
    for(j in (start:(start+c2))){
      sum <- sum + Covid_data_endFeb$newcases[j]
    }
    avg <- sum / 31
    myvec[v] <- avg
    sum <- 0
    avg <- 0
    v <- v + 1
    start <- start + c2
  }
  else
  {
    sum <- 0
    for(k in (start:(start+c1))){
      sum <- sum + Covid_data_endFeb$newcases[k]
    }
    avg <- sum / 30
    myvec[v] <- avg
    sum <- 0
    avg <- 0
    v <- v + 1
    start <- start + c1
  }
}

#covers indexes 1:13 Jan2020 - Jan 2021

newsum <- 0

for(i in (start:(start + 29))){
  newsum <- newsum + Covid_data_endFeb$newcases[i]
}
newavg <- newsum / 29
myvec[v] <- newavg
newsum <- 0
newavg <- 0 
v <- v + 1
start <- start + 29


for(i in 1:11){
  sum <- 0 
  if(i %% 2 != 0)
  {
    sum <- 0
    for(j in (start:(start+c2))){
      sum <- sum + Covid_data_endFeb$newcases[j]
    }
    avg <- sum / 31
    myvec[v] <- avg
    sum <- 0
    avg <- 0
    v <- v + 1
    start <- start + c2
  }
  else
  {
    sum <- 0
    for(k in (start:(start+c1))){
      sum <- sum + Covid_data_endFeb$newcases[k]
    }
    avg <- sum / 30
    myvec[v] <- avg
    sum <- 0
    avg <- 0
    v <- v + 1
    start <- start + c1
  }
}


for(i in (start:(start + 28))){
  newsum <- newsum + Covid_data_endFeb$newcases[i]
}
newavg <- newsum / 28
myvec[v] <- newavg
newsum <- 0
newavg <- 0 
v <- v + 1
start <- start + 28


months

myvec
for(i in 1:26){
  months$monthcases[i] <- myvec[i]
}  
months$monthcases[1] <- 0
months$monthcases[2] <- 0

months
```




```{R}

CPI_covid_data

```
```{R}

month.vid <- months

month.supp <- months

month.med <- months

month.pre <- months

month.nonpre <- months

CPI_covid_data

nrow(CPI_covid_data)

for(i in 1:26)
{
  month.vid$prices[i] <- CPI_covid_data$Rental.of.video.discs.and.other.media[i]
  month.supp$prices[i] <- CPI_covid_data$Household.cleaning.products[i]
  month.med$prices[i] <- CPI_covid_data$Medical.equipment.and.supplies[i]
  month.pre$prices[i] <- CPI_covid_data$Prescription.drugs[i]
  month.nonpre$prices[i] <- CPI_covid_data$Nonprescription.drugs[i]
}


month.vid
nrow(month.vid)
month.supp
month.med
month.pre
month.nonpre

#seperated all the prices by month into seperate dataframes for variables whose prices were most affected by case count
```
```{R}
video_rentals_plot <- ggplot(month.vid, aes(x= monthname, y = sqrt(prices), fill = monthcases)) + geom_bar(stat = "identity") + scale_fill_gradient2(low = "white", high = "black") + theme(axis.text.x = element_text(angle = 90)) + labs(title = "Video Rental and streaming companies prices vs covid cases", x = "Date", y = "Prices") 
  
video_rentals_plot

```

```{R}
cleansupp_plot <- ggplot(month.supp, aes(x= monthname, y = sqrt(prices), fill = monthcases)) + geom_bar(stat = "identity") +
scale_fill_gradient2(low = "white", high = "black", mid = "grey") + theme(axis.text.x = element_text(angle = 90))  + labs(title = "Prices of different cleaning supplies vs Covid cases", x = "Date", y = "Prices")
  
cleansupp_plot




```
```{R}
med_plot <- ggplot(month.med, aes(x= monthname, y = prices, fill = monthcases)) + geom_bar(stat = "identity") +
  scale_fill_gradient2(low = "white", high = "black", mid = "grey")
  
med_plot




```
```{R}
pres_plot <- ggplot(month.pre, aes(x= monthname, y = prices, fill = monthcases)) + geom_bar(stat = "identity") +
  scale_fill_gradient2(low = "white", high = "black", mid = "grey")
  
pres_plot




```
```{R}
nonpre_plot <- ggplot(month.nonpre, aes(x= monthname, y = prices, fill = monthcases)) + geom_bar(stat = "identity") +
  scale_fill_gradient2(low = "white", high = "black", mid = "grey")
  
nonpre_plot




```


```{r}
#the linear regression for food items
eggs <- summary(lm(Eggs ~ X7.Day.Avg.New.Cases.per.100K, data = All_Data))
bread <- summary(lm(Bread ~ X7.Day.Avg.New.Cases.per.100K, data = All_Data))
chicken <- summary(lm(Chicken ~ X7.Day.Avg.New.Cases.per.100K, data = All_Data))
food <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Chicken + Bread + Eggs, data = All_Data))

```


```{r}
#the linear regression for energy
gas <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Unleaded.regular.gasoline, data = All_Data))
electricity <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Electricity, data = All_Data))
natural_gas <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Utility..gas.service, data = All_Data))
power <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Utility..gas.service + Electricity + Unleaded.regular.gasoline, data = All_Data))

```


```{r}
#the linear regression for education/child care
day_care <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Day.care.and.preschool, data = All_Data))
college_tuition <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ College.tuition.and.fees, data = All_Data))
educational_supplies <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Educational.books.and.supplies, data = All_Data))
education <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Educational.books.and.supplies + College.tuition.and.fees + Day.care.and.preschool, data = All_Data))
```


```{r}
#the linear regression for transportation items
parking_fees <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Parking.fees.and.tolls, data = All_Data))
motor_insurance <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Motor.vehicle.insurance, data = All_Data))
airline_fares <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Airline.fares, data = All_Data))
transportation <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Airline.fares + Motor.vehicle.insurance + Parking.fees.and.tolls, data = All_Data))
#transportation
```


```{r}
#the linear regression for medical items items
prescription_drugs <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Prescription.drugs, data = All_Data))
nonprescription_drugs <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Nonprescription.drugs, data = All_Data))
medical_supplies <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Medical.equipment.and.supplies, data = All_Data))
medicine <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Medical.equipment.and.supplies + Nonprescription.drugs + Prescription.drugs, data = All_Data))

#graph for prescription_durgs
prescription_drugs_plot <- ggplot(aes(x = CPI_data$Prescription.drugs, y = Clean_Covid_Data$X7.Day.Avg.New.Cases.per.100K))+geom_histogram()

```


```{r}
#the linear regression for entertainment items
music <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Recorded.music.and.music.subscriptions, data = All_Data))
cable_tv <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Cable.and.satellite.television.service, data = All_Data))
video_rentals <- summary(lm(Rental.of.video.discs.and.other.media ~ X7.Day.Avg.New.Cases.per.100K, data = All_Data))
books <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Recreational.books, data = All_Data))
entertainment <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Recreational.books + Rental.of.video.discs.and.other.media + Cable.and.satellite.television.service + Recorded.music.and.music.subscriptions, data = All_Data))

```


```{r}
#the linear regression for general home items
outdoor_equipment <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Outdoor.equipment.and.supplies, data = All_Data))
indoor_plants <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Indoor.plants.and.flowers, data = All_Data))
cleaning_supplies <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Household.cleaning.products, data = All_Data))
rent <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Rent.of.primary.residence, data = All_Data))
home <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ Rent.of.primary.residence + Household.cleaning.products + Indoor.plants.and.flowers + Outdoor.equipment.and.supplies, data = All_Data))

```

```{r}
#Total CPI linear regression for US and Finland
US_total <- summary(lm(X7.Day.Avg.New.Cases.per.100K ~ All.items, data = All_Data))
Alaska_Total <- summary(lm(All.Items ~ All.Cases, data = Alaska_data))
Finland_Total <- summary(lm(Point.figure ~ New_cases, data = Finland_data))
 
```

Graphs
```{r}
#Video rental
All_Data %>% ggplot(aes(Date, sqrt(Rental.of.video.discs.and.other.media), fill = X7.Day.Avg.New.Cases.per.100K)) + geom_bar(stat = "identity") + scale_fill_gradient2(low = "white", high = "black") + theme(axis.text.x = element_text(angle = 90)) + labs(title = "Video Rental and streaming companies prices vs covid cases", x = "Date", y = "Prices") 

All_Data %>% ggplot(aes(X7.Day.Avg.New.Cases.per.100K, Rental.of.video.discs.and.other.media)) + geom_point() + geom_abline(aes(intercept=137, slope = 4.443e-02))
```

